-- GENERATED FILE — do not edit.
--
-- Written by scripts/generate-seed.ts from SEED_CATALOG in @pashki/core.
-- Regenerate with: pnpm --filter @pashki/db gen:seed
--
-- 65 ingredients, 183 package sizes.
--
-- Idempotent: `supabase db reset` runs this after the migrations, and running it
-- again upserts rather than duplicating. Both tables have the unique constraints
-- that makes that possible — ingredients.key and (ingredient_id, system, label).
--
-- base_amount and can_size are in the dimension's base unit, millilitres or
-- grams. grams_per_cup is what lets a volume measure merge into an item sold by
-- weight. Never do arithmetic on written units.

begin;

insert into public.ingredients
  (key, canonical_name, aliases, aisle, dimension, grams_per_cup, can_size,
   grams_each, kcal_per_100g, energy_fdc_id)
values
  ('heavy-cream', 'heavy cream', array['heavy whipping cream', 'whipping cream'], 'Dairy', 'volume', 238, null, null, 340, '170859'),
  ('half-and-half', 'half and half', array['half & half'], 'Dairy', 'volume', null, null, null, null, null),
  ('double-cream', 'double cream', array['extra thick double cream'], 'Dairy', 'volume', 237, null, null, 449, null),
  ('single-cream', 'single cream', array['pouring cream'], 'Dairy', 'volume', 240, null, null, 195, '170857'),
  ('milk', 'whole milk', array['full fat milk', 'milk'], 'Dairy', 'volume', 244, null, null, 61, '171265'),
  ('semi-skimmed-milk', 'semi skimmed milk', array['semi-skimmed milk', '2% milk', 'reduced fat milk'], 'Dairy', 'volume', 244, null, null, 50, '171267'),
  ('skimmed-milk', 'skimmed milk', array['skim milk', 'fat free milk', 'nonfat milk'], 'Dairy', 'volume', 245, null, null, 34, '171269'),
  ('buttermilk', 'buttermilk', '{}'::text[], 'Dairy', 'volume', null, null, null, null, null),
  ('sour-cream', 'sour cream', '{}'::text[], 'Dairy', 'weight', 230, null, null, null, null),
  ('yogurt', 'plain yogurt', array['natural yogurt', 'yoghurt', 'yogurt'], 'Dairy', 'weight', 245, null, null, 61, '171284'),
  ('cheddar', 'mature cheddar', array['shredded cheddar', 'grated cheddar', 'cheddar'], 'Dairy', 'weight', 113, null, null, 408, '328637'),
  ('mozzarella', 'shredded mozzarella', array['grated mozzarella', 'mozzarella'], 'Dairy', 'weight', 113, null, null, 299, '170845'),
  ('greek-yogurt', 'greek yogurt', array['greek yoghurt', 'strained yogurt'], 'Dairy', 'weight', 245, null, null, 97, '171304'),
  ('butter', 'unsalted butter', array['salted butter', 'butter'], 'Dairy', 'weight', 227, null, null, 717, '173410'),
  ('cream-cheese', 'cream cheese', '{}'::text[], 'Dairy', 'weight', 232, null, null, null, null),
  ('shredded-cheese', 'monterey jack', array['shredded cheese', 'grated cheese'], 'Dairy', 'weight', 113, null, null, null, null),
  ('parmesan', 'parmigiano reggiano', array['grated parmesan', 'parmesan', 'pecorino'], 'Dairy', 'weight', 100, null, null, 392, '170848'),
  ('feta', 'feta', '{}'::text[], 'Dairy', 'weight', 150, null, null, null, null),
  ('eggs', 'large egg', array['large eggs', 'eggs', 'egg'], 'Dairy', 'count', null, null, 50, 143, '171287'),
  ('chicken-breast', 'boneless skinless chicken breast', array['chicken breasts', 'chicken breast'], 'Meat & Seafood', 'weight', null, null, null, null, null),
  ('chicken-thighs', 'boneless chicken thighs', array['chicken thighs', 'chicken thigh'], 'Meat & Seafood', 'weight', null, null, null, 121, '173627'),
  ('ground-beef', 'ground beef', array['ground chuck', 'beef mince', 'hamburger'], 'Meat & Seafood', 'weight', null, null, null, 254, '174036'),
  ('lean-ground-beef', 'lean ground beef', array['extra lean mince', 'lean beef mince', '5% fat mince'], 'Meat & Seafood', 'weight', null, null, null, 176, '174030'),
  ('ground-turkey', 'ground turkey', '{}'::text[], 'Meat & Seafood', 'weight', null, null, null, null, null),
  ('sausage', 'italian sausage', array['sausage'], 'Meat & Seafood', 'weight', null, null, null, null, null),
  ('bacon', 'bacon', '{}'::text[], 'Meat & Seafood', 'weight', null, null, null, null, null),
  ('salmon', 'salmon fillets', array['salmon fillet', 'salmon'], 'Meat & Seafood', 'weight', null, null, null, null, null),
  ('shrimp', 'shrimp', array['prawns'], 'Meat & Seafood', 'weight', null, null, null, 85, '175179'),
  ('onion', 'yellow onion', array['white onion', 'red onion', 'onions', 'onion'], 'Produce', 'count', null, null, 110, 40, '170000'),
  ('garlic', 'garlic', array['garlic cloves', 'garlic clove'], 'Produce', 'clove', null, null, 3, 143, '1104647'),
  ('lemon', 'lemon', array['lemons'], 'Produce', 'count', null, null, 58, 29, '167746'),
  ('lime', 'lime', array['limes'], 'Produce', 'count', null, null, null, null, null),
  ('potatoes', 'russet potatoes', array['yukon gold potatoes', 'baby potatoes', 'potatoes', 'potato'], 'Produce', 'weight', null, null, null, 77, '170026'),
  ('carrots', 'carrots', array['carrot'], 'Produce', 'weight', null, null, null, null, null),
  ('celery', 'celery', '{}'::text[], 'Produce', 'count', null, null, null, null, null),
  ('bell-pepper', 'red bell pepper', array['green bell pepper', 'bell peppers', 'bell pepper'], 'Produce', 'count', null, null, 119, 26, '170108'),
  ('spinach', 'baby spinach', array['spinach'], 'Produce', 'weight', null, null, null, null, null),
  ('tomatoes', 'roma tomato', array['roma tomatoes', 'cherry tomatoes', 'cherry tomato', 'tomatoes', 'tomato'], 'Produce', 'count', null, null, 123, 18, '170457'),
  ('mushrooms', 'cremini mushrooms', array['button mushrooms', 'mushrooms'], 'Produce', 'weight', null, null, null, 22, '169251'),
  ('broccoli', 'broccoli', '{}'::text[], 'Produce', 'count', null, null, null, null, null),
  ('avocado', 'avocado', array['avocados'], 'Produce', 'count', null, null, null, null, null),
  ('cilantro', 'fresh cilantro', array['cilantro', 'coriander'], 'Produce', 'bunch', null, null, null, null, null),
  ('parsley', 'fresh parsley', array['parsley'], 'Produce', 'bunch', null, null, null, null, null),
  ('basil', 'fresh basil', array['basil'], 'Produce', 'bunch', null, null, 25, 23, '172232'),
  ('green-onions', 'green onions', array['scallions', 'spring onions', 'green onion'], 'Produce', 'bunch', null, null, null, null, null),
  ('olive-oil', 'extra virgin olive oil', array['olive oil'], 'Pantry', 'volume', 216, null, null, 884, '171413'),
  ('flour', 'all purpose flour', array['all-purpose flour', 'plain flour', 'flour'], 'Pantry', 'weight', 125, null, null, 364, '168894'),
  ('sugar', 'granulated sugar', array['caster sugar', 'sugar'], 'Pantry', 'weight', 200, null, null, 387, '169655'),
  ('brown-sugar', 'brown sugar', '{}'::text[], 'Pantry', 'weight', 213, null, null, 380, '168833'),
  ('rice', 'jasmine rice', array['basmati rice', 'white rice', 'rice'], 'Pantry', 'weight', 185, null, null, 365, '168877'),
  ('pasta', 'spaghetti', array['rigatoni', 'fettuccine', 'linguine', 'penne', 'pasta'], 'Pantry', 'weight', null, null, null, 371, '169736'),
  ('canned-tomatoes', 'crushed tomatoes', array['diced tomatoes', 'canned tomatoes', 'chopped tomatoes', 'tomato sauce', 'passata'], 'Pantry', 'weight', 240, 425, null, 18, '333281'),
  ('tomato-paste', 'tomato paste', array['tomato puree'], 'Pantry', 'weight', 260, 170, null, null, null),
  ('sun-dried-tomatoes', 'sun dried tomatoes', array['sun-dried tomatoes'], 'Pantry', 'weight', 110, null, null, null, null),
  ('broth', 'chicken broth', array['chicken stock', 'vegetable broth', 'vegetable stock', 'beef broth', 'broth', 'stock'], 'Pantry', 'volume', 240, 429, null, 6, '174536'),
  ('coconut-milk', 'coconut milk', '{}'::text[], 'Pantry', 'volume', null, 400, null, null, null),
  ('beans', 'black beans', array['kidney beans', 'chickpeas', 'cannellini beans', 'pinto beans'], 'Pantry', 'weight', 180, 425, null, null, null),
  ('soy-sauce', 'soy sauce', '{}'::text[], 'Pantry', 'volume', null, null, null, null, null),
  ('honey', 'honey', '{}'::text[], 'Pantry', 'volume', 340, null, null, 304, '169640'),
  ('maple-syrup', 'maple syrup', '{}'::text[], 'Pantry', 'volume', 322, null, null, 260, '169661'),
  ('flour-tortillas', 'flour tortilla', array['flour tortillas', 'wheat tortilla', 'wheat tortillas', 'wrap', 'wraps'], 'Bakery', 'count', null, null, 45, 306, '175037'),
  ('corn-tortillas', 'corn tortilla', array['corn tortillas'], 'Bakery', 'count', null, null, 26, 218, '175036'),
  ('tortillas', 'tortilla', array['tortillas'], 'Bakery', 'count', null, null, null, null, null),
  ('bread', 'sandwich bread', array['baguette', 'bread'], 'Bakery', 'count', null, null, null, null, null),
  ('frozen-peas', 'frozen peas', array['frozen corn', 'frozen vegetables'], 'Frozen', 'weight', null, null, null, null, null)
on conflict (key) do update set
  canonical_name = excluded.canonical_name,
  aliases        = excluded.aliases,
  aisle          = excluded.aisle,
  dimension      = excluded.dimension,
  grams_per_cup  = excluded.grams_per_cup,
  grams_each     = excluded.grams_each,
  kcal_per_100g  = excluded.kcal_per_100g,
  energy_fdc_id  = excluded.energy_fdc_id,
  can_size       = excluded.can_size,
  updated_at     = now();

-- Packages are keyed to their ingredient by catalog key rather than by a uuid, so
-- this file carries no generated ids and stays stable between runs.
insert into public.grocery_packages (ingredient_id, system, label, base_amount, sort_order)
select i.id, seed.system, seed.label, seed.base_amount, seed.sort_order
from (values
  ('heavy-cream', 'us', '½ pint (8 oz)', 237, 0),
  ('heavy-cream', 'us', 'pint (16 oz)', 473, 1),
  ('heavy-cream', 'us', 'quart (32 oz)', 946, 2),
  ('heavy-cream', 'metric', '300 ml pot', 300, 0),
  ('heavy-cream', 'metric', '600 ml pot', 600, 1),
  ('half-and-half', 'us', 'pint', 473, 0),
  ('half-and-half', 'us', 'quart', 946, 1),
  ('half-and-half', 'metric', '300 ml pot', 300, 0),
  ('double-cream', 'us', '300 ml pot', 300, 0),
  ('double-cream', 'us', '600 ml pot', 600, 1),
  ('single-cream', 'us', '300 ml pot', 300, 0),
  ('single-cream', 'us', '600 ml pot', 600, 1),
  ('milk', 'us', 'quart', 946, 0),
  ('milk', 'us', '½ gallon', 1893, 1),
  ('milk', 'us', 'gallon', 3785, 2),
  ('milk', 'metric', '500 ml', 500, 0),
  ('milk', 'metric', '1 l', 1000, 1),
  ('milk', 'metric', '2 l', 2000, 2),
  ('semi-skimmed-milk', 'us', 'quart', 946, 0),
  ('semi-skimmed-milk', 'us', '2 pint', 1136, 1),
  ('skimmed-milk', 'us', 'quart', 946, 0),
  ('skimmed-milk', 'us', '2 pint', 1136, 1),
  ('buttermilk', 'us', 'pint', 473, 0),
  ('buttermilk', 'us', 'quart', 946, 1),
  ('buttermilk', 'metric', '284 ml pot', 284, 0),
  ('sour-cream', 'us', '8 oz tub', 227, 0),
  ('sour-cream', 'us', '16 oz tub', 454, 1),
  ('sour-cream', 'metric', '300 g pot', 300, 0),
  ('yogurt', 'us', '5.3 oz pot', 150, 0),
  ('yogurt', 'us', '16 oz tub', 454, 1),
  ('yogurt', 'us', '32 oz tub', 907, 2),
  ('yogurt', 'metric', '500 g pot', 500, 0),
  ('yogurt', 'metric', '1 kg pot', 1000, 1),
  ('cheddar', 'us', '8 oz block', 227, 0),
  ('cheddar', 'us', '16 oz block', 454, 1),
  ('mozzarella', 'us', '8 oz ball', 227, 0),
  ('mozzarella', 'us', '16 oz bag', 454, 1),
  ('greek-yogurt', 'us', '5.3 oz pot', 150, 0),
  ('greek-yogurt', 'us', '32 oz tub', 907, 1),
  ('butter', 'us', '1 stick', 113, 0),
  ('butter', 'us', '1 lb (4 sticks)', 454, 1),
  ('butter', 'metric', '250 g block', 250, 0),
  ('cream-cheese', 'us', '8 oz block', 227, 0),
  ('cream-cheese', 'metric', '180 g tub', 180, 0),
  ('cream-cheese', 'metric', '280 g tub', 280, 1),
  ('shredded-cheese', 'us', '8 oz bag', 227, 0),
  ('shredded-cheese', 'us', '16 oz bag', 454, 1),
  ('shredded-cheese', 'metric', '200 g bag', 200, 0),
  ('parmesan', 'us', '5 oz wedge', 142, 0),
  ('parmesan', 'us', '8 oz wedge', 227, 1),
  ('parmesan', 'metric', '100 g piece', 100, 0),
  ('parmesan', 'metric', '200 g piece', 200, 1),
  ('feta', 'us', '6 oz', 170, 0),
  ('feta', 'us', '8 oz', 227, 1),
  ('feta', 'metric', '200 g block', 200, 0),
  ('eggs', 'us', 'half dozen', 6, 0),
  ('eggs', 'us', 'dozen', 12, 1),
  ('eggs', 'us', '18-count', 18, 2),
  ('eggs', 'metric', 'box of 6', 6, 0),
  ('eggs', 'metric', 'box of 12', 12, 1),
  ('chicken-breast', 'us', '1 lb', 454, 0),
  ('chicken-breast', 'us', '2 lb', 907, 1),
  ('chicken-breast', 'us', '3 lb family pack', 1361, 2),
  ('chicken-breast', 'metric', '300 g pack', 300, 0),
  ('chicken-breast', 'metric', '600 g pack', 600, 1),
  ('chicken-thighs', 'us', '1 lb', 454, 0),
  ('chicken-thighs', 'us', '2 lb', 907, 1),
  ('chicken-thighs', 'metric', '500 g pack', 500, 0),
  ('chicken-thighs', 'metric', '1 kg pack', 1000, 1),
  ('ground-beef', 'us', '1 lb', 454, 0),
  ('ground-beef', 'us', '2 lb', 907, 1),
  ('ground-beef', 'metric', '500 g pack', 500, 0),
  ('lean-ground-beef', 'us', '1 lb', 454, 0),
  ('lean-ground-beef', 'us', '500 g', 500, 1),
  ('ground-turkey', 'us', '1 lb', 454, 0),
  ('ground-turkey', 'metric', '500 g pack', 500, 0),
  ('sausage', 'us', '1 lb', 454, 0),
  ('bacon', 'us', '12 oz pack', 340, 0),
  ('bacon', 'us', '1 lb pack', 454, 1),
  ('salmon', 'us', '1 lb', 454, 0),
  ('salmon', 'us', '1½ lb', 680, 1),
  ('salmon', 'metric', '240 g (2 fillets)', 240, 0),
  ('shrimp', 'us', '1 lb bag', 454, 0),
  ('onion', 'us', 'loose', 1, 0),
  ('onion', 'us', '3 lb bag (~6)', 6, 1),
  ('onion', 'metric', 'loose', 1, 0),
  ('onion', 'metric', '1 kg net (~7)', 7, 1),
  ('garlic', 'us', '1 head (~10 cloves)', 10, 0),
  ('garlic', 'us', '3-pack heads', 30, 1),
  ('garlic', 'metric', '1 bulb (~10 cloves)', 10, 0),
  ('garlic', 'metric', '3-pack bulbs', 30, 1),
  ('lemon', 'us', 'loose', 1, 0),
  ('lemon', 'us', 'bag of 5', 5, 1),
  ('lemon', 'metric', 'loose', 1, 0),
  ('lemon', 'metric', 'pack of 4', 4, 1),
  ('lime', 'us', 'loose', 1, 0),
  ('lime', 'us', 'bag of 5', 5, 1),
  ('lime', 'metric', 'loose', 1, 0),
  ('lime', 'metric', 'pack of 5', 5, 1),
  ('potatoes', 'us', 'loose lb', 454, 0),
  ('potatoes', 'us', '5 lb bag', 2268, 1),
  ('potatoes', 'metric', '1 kg bag', 1000, 0),
  ('potatoes', 'metric', '2.5 kg bag', 2500, 1),
  ('carrots', 'us', '1 lb bag', 454, 0),
  ('carrots', 'us', '2 lb bag', 907, 1),
  ('carrots', 'metric', '500 g bag', 500, 0),
  ('carrots', 'metric', '1 kg bag', 1000, 1),
  ('celery', 'us', '1 bunch (~8 stalks)', 8, 0),
  ('bell-pepper', 'us', 'loose', 1, 0),
  ('bell-pepper', 'us', '3-pack', 3, 1),
  ('spinach', 'us', '5 oz box', 142, 0),
  ('spinach', 'us', '10 oz box', 283, 1),
  ('spinach', 'metric', '250 g bag', 250, 0),
  ('tomatoes', 'us', 'loose', 1, 0),
  ('tomatoes', 'us', 'pint container', 12, 1),
  ('tomatoes', 'metric', 'loose', 1, 0),
  ('tomatoes', 'metric', '6-pack', 6, 1),
  ('mushrooms', 'us', '8 oz pack', 227, 0),
  ('mushrooms', 'us', '16 oz pack', 454, 1),
  ('mushrooms', 'metric', '250 g punnet', 250, 0),
  ('mushrooms', 'metric', '500 g punnet', 500, 1),
  ('broccoli', 'us', '1 crown', 1, 0),
  ('avocado', 'us', 'loose', 1, 0),
  ('avocado', 'us', 'bag of 4', 4, 1),
  ('avocado', 'metric', 'loose', 1, 0),
  ('avocado', 'metric', 'pack of 4', 4, 1),
  ('cilantro', 'us', '1 bunch', 1, 0),
  ('parsley', 'us', '1 bunch', 1, 0),
  ('basil', 'us', '1 packet', 1, 0),
  ('green-onions', 'us', '1 bunch', 1, 0),
  ('olive-oil', 'us', '17 oz bottle', 500, 0),
  ('olive-oil', 'us', '34 oz bottle', 1000, 1),
  ('olive-oil', 'metric', '500 ml bottle', 500, 0),
  ('olive-oil', 'metric', '1 l bottle', 1000, 1),
  ('flour', 'us', '2 lb bag', 907, 0),
  ('flour', 'us', '5 lb bag', 2268, 1),
  ('flour', 'metric', '500 g bag', 500, 0),
  ('flour', 'metric', '1.5 kg bag', 1500, 1),
  ('sugar', 'us', '2 lb bag', 907, 0),
  ('sugar', 'us', '4 lb bag', 1814, 1),
  ('sugar', 'metric', '500 g bag', 500, 0),
  ('sugar', 'metric', '1 kg bag', 1000, 1),
  ('brown-sugar', 'us', '1 lb bag', 454, 0),
  ('brown-sugar', 'us', '2 lb bag', 907, 1),
  ('brown-sugar', 'metric', '500 g bag', 500, 0),
  ('rice', 'us', '2 lb bag', 907, 0),
  ('rice', 'us', '5 lb bag', 2268, 1),
  ('rice', 'metric', '500 g bag', 500, 0),
  ('rice', 'metric', '1 kg bag', 1000, 1),
  ('pasta', 'us', '1 lb box', 454, 0),
  ('pasta', 'metric', '500 g pack', 500, 0),
  ('canned-tomatoes', 'us', '15 oz can', 425, 0),
  ('canned-tomatoes', 'us', '28 oz can', 794, 1),
  ('canned-tomatoes', 'metric', '400 g tin', 400, 0),
  ('tomato-paste', 'us', '6 oz can', 170, 0),
  ('tomato-paste', 'metric', '200 g tube', 200, 0),
  ('sun-dried-tomatoes', 'us', '8 oz jar', 227, 0),
  ('broth', 'us', '14.5 oz can', 429, 0),
  ('broth', 'us', '32 oz carton', 946, 1),
  ('broth', 'metric', '500 ml carton', 500, 0),
  ('broth', 'metric', '1 l carton', 1000, 1),
  ('coconut-milk', 'us', '13.5 oz can', 400, 0),
  ('coconut-milk', 'metric', '400 ml tin', 400, 0),
  ('beans', 'us', '15 oz can', 425, 0),
  ('beans', 'metric', '400 g tin', 400, 0),
  ('soy-sauce', 'us', '10 oz bottle', 296, 0),
  ('soy-sauce', 'metric', '150 ml bottle', 150, 0),
  ('soy-sauce', 'metric', '500 ml bottle', 500, 1),
  ('honey', 'us', '12 oz jar', 355, 0),
  ('maple-syrup', 'us', '8 oz bottle', 237, 0),
  ('maple-syrup', 'us', '12 oz bottle', 355, 1),
  ('maple-syrup', 'metric', '250 ml bottle', 250, 0),
  ('flour-tortillas', 'us', 'pack of 8', 8, 0),
  ('flour-tortillas', 'us', 'pack of 10', 10, 1),
  ('corn-tortillas', 'us', 'pack of 12', 12, 0),
  ('corn-tortillas', 'us', 'pack of 30', 30, 1),
  ('tortillas', 'us', 'pack of 8', 8, 0),
  ('tortillas', 'us', 'pack of 12', 12, 1),
  ('bread', 'us', '1 loaf', 1, 0),
  ('bread', 'metric', '1 loaf', 1, 0),
  ('frozen-peas', 'us', '10 oz bag', 283, 0),
  ('frozen-peas', 'us', '16 oz bag', 454, 1),
  ('frozen-peas', 'metric', '900 g bag', 900, 0)
) as seed(ingredient_key, system, label, base_amount, sort_order)
join public.ingredients i on i.key = seed.ingredient_key
on conflict (ingredient_id, system, label) do update set
  base_amount = excluded.base_amount,
  sort_order  = excluded.sort_order,
  updated_at  = now();

-- A package list that shrank in SEED_CATALOG must shrink here too, or the catalog
-- would keep offering a size that no longer exists. Anything not in this run's
-- values list is removed.
delete from public.grocery_packages gp
using public.ingredients i
where gp.ingredient_id = i.id
  and (i.key, gp.system, gp.label) not in (
    select seed.ingredient_key, seed.system, seed.label
    from (values
  ('heavy-cream', 'us', '½ pint (8 oz)', 237, 0),
  ('heavy-cream', 'us', 'pint (16 oz)', 473, 1),
  ('heavy-cream', 'us', 'quart (32 oz)', 946, 2),
  ('heavy-cream', 'metric', '300 ml pot', 300, 0),
  ('heavy-cream', 'metric', '600 ml pot', 600, 1),
  ('half-and-half', 'us', 'pint', 473, 0),
  ('half-and-half', 'us', 'quart', 946, 1),
  ('half-and-half', 'metric', '300 ml pot', 300, 0),
  ('double-cream', 'us', '300 ml pot', 300, 0),
  ('double-cream', 'us', '600 ml pot', 600, 1),
  ('single-cream', 'us', '300 ml pot', 300, 0),
  ('single-cream', 'us', '600 ml pot', 600, 1),
  ('milk', 'us', 'quart', 946, 0),
  ('milk', 'us', '½ gallon', 1893, 1),
  ('milk', 'us', 'gallon', 3785, 2),
  ('milk', 'metric', '500 ml', 500, 0),
  ('milk', 'metric', '1 l', 1000, 1),
  ('milk', 'metric', '2 l', 2000, 2),
  ('semi-skimmed-milk', 'us', 'quart', 946, 0),
  ('semi-skimmed-milk', 'us', '2 pint', 1136, 1),
  ('skimmed-milk', 'us', 'quart', 946, 0),
  ('skimmed-milk', 'us', '2 pint', 1136, 1),
  ('buttermilk', 'us', 'pint', 473, 0),
  ('buttermilk', 'us', 'quart', 946, 1),
  ('buttermilk', 'metric', '284 ml pot', 284, 0),
  ('sour-cream', 'us', '8 oz tub', 227, 0),
  ('sour-cream', 'us', '16 oz tub', 454, 1),
  ('sour-cream', 'metric', '300 g pot', 300, 0),
  ('yogurt', 'us', '5.3 oz pot', 150, 0),
  ('yogurt', 'us', '16 oz tub', 454, 1),
  ('yogurt', 'us', '32 oz tub', 907, 2),
  ('yogurt', 'metric', '500 g pot', 500, 0),
  ('yogurt', 'metric', '1 kg pot', 1000, 1),
  ('cheddar', 'us', '8 oz block', 227, 0),
  ('cheddar', 'us', '16 oz block', 454, 1),
  ('mozzarella', 'us', '8 oz ball', 227, 0),
  ('mozzarella', 'us', '16 oz bag', 454, 1),
  ('greek-yogurt', 'us', '5.3 oz pot', 150, 0),
  ('greek-yogurt', 'us', '32 oz tub', 907, 1),
  ('butter', 'us', '1 stick', 113, 0),
  ('butter', 'us', '1 lb (4 sticks)', 454, 1),
  ('butter', 'metric', '250 g block', 250, 0),
  ('cream-cheese', 'us', '8 oz block', 227, 0),
  ('cream-cheese', 'metric', '180 g tub', 180, 0),
  ('cream-cheese', 'metric', '280 g tub', 280, 1),
  ('shredded-cheese', 'us', '8 oz bag', 227, 0),
  ('shredded-cheese', 'us', '16 oz bag', 454, 1),
  ('shredded-cheese', 'metric', '200 g bag', 200, 0),
  ('parmesan', 'us', '5 oz wedge', 142, 0),
  ('parmesan', 'us', '8 oz wedge', 227, 1),
  ('parmesan', 'metric', '100 g piece', 100, 0),
  ('parmesan', 'metric', '200 g piece', 200, 1),
  ('feta', 'us', '6 oz', 170, 0),
  ('feta', 'us', '8 oz', 227, 1),
  ('feta', 'metric', '200 g block', 200, 0),
  ('eggs', 'us', 'half dozen', 6, 0),
  ('eggs', 'us', 'dozen', 12, 1),
  ('eggs', 'us', '18-count', 18, 2),
  ('eggs', 'metric', 'box of 6', 6, 0),
  ('eggs', 'metric', 'box of 12', 12, 1),
  ('chicken-breast', 'us', '1 lb', 454, 0),
  ('chicken-breast', 'us', '2 lb', 907, 1),
  ('chicken-breast', 'us', '3 lb family pack', 1361, 2),
  ('chicken-breast', 'metric', '300 g pack', 300, 0),
  ('chicken-breast', 'metric', '600 g pack', 600, 1),
  ('chicken-thighs', 'us', '1 lb', 454, 0),
  ('chicken-thighs', 'us', '2 lb', 907, 1),
  ('chicken-thighs', 'metric', '500 g pack', 500, 0),
  ('chicken-thighs', 'metric', '1 kg pack', 1000, 1),
  ('ground-beef', 'us', '1 lb', 454, 0),
  ('ground-beef', 'us', '2 lb', 907, 1),
  ('ground-beef', 'metric', '500 g pack', 500, 0),
  ('lean-ground-beef', 'us', '1 lb', 454, 0),
  ('lean-ground-beef', 'us', '500 g', 500, 1),
  ('ground-turkey', 'us', '1 lb', 454, 0),
  ('ground-turkey', 'metric', '500 g pack', 500, 0),
  ('sausage', 'us', '1 lb', 454, 0),
  ('bacon', 'us', '12 oz pack', 340, 0),
  ('bacon', 'us', '1 lb pack', 454, 1),
  ('salmon', 'us', '1 lb', 454, 0),
  ('salmon', 'us', '1½ lb', 680, 1),
  ('salmon', 'metric', '240 g (2 fillets)', 240, 0),
  ('shrimp', 'us', '1 lb bag', 454, 0),
  ('onion', 'us', 'loose', 1, 0),
  ('onion', 'us', '3 lb bag (~6)', 6, 1),
  ('onion', 'metric', 'loose', 1, 0),
  ('onion', 'metric', '1 kg net (~7)', 7, 1),
  ('garlic', 'us', '1 head (~10 cloves)', 10, 0),
  ('garlic', 'us', '3-pack heads', 30, 1),
  ('garlic', 'metric', '1 bulb (~10 cloves)', 10, 0),
  ('garlic', 'metric', '3-pack bulbs', 30, 1),
  ('lemon', 'us', 'loose', 1, 0),
  ('lemon', 'us', 'bag of 5', 5, 1),
  ('lemon', 'metric', 'loose', 1, 0),
  ('lemon', 'metric', 'pack of 4', 4, 1),
  ('lime', 'us', 'loose', 1, 0),
  ('lime', 'us', 'bag of 5', 5, 1),
  ('lime', 'metric', 'loose', 1, 0),
  ('lime', 'metric', 'pack of 5', 5, 1),
  ('potatoes', 'us', 'loose lb', 454, 0),
  ('potatoes', 'us', '5 lb bag', 2268, 1),
  ('potatoes', 'metric', '1 kg bag', 1000, 0),
  ('potatoes', 'metric', '2.5 kg bag', 2500, 1),
  ('carrots', 'us', '1 lb bag', 454, 0),
  ('carrots', 'us', '2 lb bag', 907, 1),
  ('carrots', 'metric', '500 g bag', 500, 0),
  ('carrots', 'metric', '1 kg bag', 1000, 1),
  ('celery', 'us', '1 bunch (~8 stalks)', 8, 0),
  ('bell-pepper', 'us', 'loose', 1, 0),
  ('bell-pepper', 'us', '3-pack', 3, 1),
  ('spinach', 'us', '5 oz box', 142, 0),
  ('spinach', 'us', '10 oz box', 283, 1),
  ('spinach', 'metric', '250 g bag', 250, 0),
  ('tomatoes', 'us', 'loose', 1, 0),
  ('tomatoes', 'us', 'pint container', 12, 1),
  ('tomatoes', 'metric', 'loose', 1, 0),
  ('tomatoes', 'metric', '6-pack', 6, 1),
  ('mushrooms', 'us', '8 oz pack', 227, 0),
  ('mushrooms', 'us', '16 oz pack', 454, 1),
  ('mushrooms', 'metric', '250 g punnet', 250, 0),
  ('mushrooms', 'metric', '500 g punnet', 500, 1),
  ('broccoli', 'us', '1 crown', 1, 0),
  ('avocado', 'us', 'loose', 1, 0),
  ('avocado', 'us', 'bag of 4', 4, 1),
  ('avocado', 'metric', 'loose', 1, 0),
  ('avocado', 'metric', 'pack of 4', 4, 1),
  ('cilantro', 'us', '1 bunch', 1, 0),
  ('parsley', 'us', '1 bunch', 1, 0),
  ('basil', 'us', '1 packet', 1, 0),
  ('green-onions', 'us', '1 bunch', 1, 0),
  ('olive-oil', 'us', '17 oz bottle', 500, 0),
  ('olive-oil', 'us', '34 oz bottle', 1000, 1),
  ('olive-oil', 'metric', '500 ml bottle', 500, 0),
  ('olive-oil', 'metric', '1 l bottle', 1000, 1),
  ('flour', 'us', '2 lb bag', 907, 0),
  ('flour', 'us', '5 lb bag', 2268, 1),
  ('flour', 'metric', '500 g bag', 500, 0),
  ('flour', 'metric', '1.5 kg bag', 1500, 1),
  ('sugar', 'us', '2 lb bag', 907, 0),
  ('sugar', 'us', '4 lb bag', 1814, 1),
  ('sugar', 'metric', '500 g bag', 500, 0),
  ('sugar', 'metric', '1 kg bag', 1000, 1),
  ('brown-sugar', 'us', '1 lb bag', 454, 0),
  ('brown-sugar', 'us', '2 lb bag', 907, 1),
  ('brown-sugar', 'metric', '500 g bag', 500, 0),
  ('rice', 'us', '2 lb bag', 907, 0),
  ('rice', 'us', '5 lb bag', 2268, 1),
  ('rice', 'metric', '500 g bag', 500, 0),
  ('rice', 'metric', '1 kg bag', 1000, 1),
  ('pasta', 'us', '1 lb box', 454, 0),
  ('pasta', 'metric', '500 g pack', 500, 0),
  ('canned-tomatoes', 'us', '15 oz can', 425, 0),
  ('canned-tomatoes', 'us', '28 oz can', 794, 1),
  ('canned-tomatoes', 'metric', '400 g tin', 400, 0),
  ('tomato-paste', 'us', '6 oz can', 170, 0),
  ('tomato-paste', 'metric', '200 g tube', 200, 0),
  ('sun-dried-tomatoes', 'us', '8 oz jar', 227, 0),
  ('broth', 'us', '14.5 oz can', 429, 0),
  ('broth', 'us', '32 oz carton', 946, 1),
  ('broth', 'metric', '500 ml carton', 500, 0),
  ('broth', 'metric', '1 l carton', 1000, 1),
  ('coconut-milk', 'us', '13.5 oz can', 400, 0),
  ('coconut-milk', 'metric', '400 ml tin', 400, 0),
  ('beans', 'us', '15 oz can', 425, 0),
  ('beans', 'metric', '400 g tin', 400, 0),
  ('soy-sauce', 'us', '10 oz bottle', 296, 0),
  ('soy-sauce', 'metric', '150 ml bottle', 150, 0),
  ('soy-sauce', 'metric', '500 ml bottle', 500, 1),
  ('honey', 'us', '12 oz jar', 355, 0),
  ('maple-syrup', 'us', '8 oz bottle', 237, 0),
  ('maple-syrup', 'us', '12 oz bottle', 355, 1),
  ('maple-syrup', 'metric', '250 ml bottle', 250, 0),
  ('flour-tortillas', 'us', 'pack of 8', 8, 0),
  ('flour-tortillas', 'us', 'pack of 10', 10, 1),
  ('corn-tortillas', 'us', 'pack of 12', 12, 0),
  ('corn-tortillas', 'us', 'pack of 30', 30, 1),
  ('tortillas', 'us', 'pack of 8', 8, 0),
  ('tortillas', 'us', 'pack of 12', 12, 1),
  ('bread', 'us', '1 loaf', 1, 0),
  ('bread', 'metric', '1 loaf', 1, 0),
  ('frozen-peas', 'us', '10 oz bag', 283, 0),
  ('frozen-peas', 'us', '16 oz bag', 454, 1),
  ('frozen-peas', 'metric', '900 g bag', 900, 0)
    ) as seed(ingredient_key, system, label, base_amount, sort_order)
  );

commit;
