-- GENERATED FILE — do not edit.
--
-- Written by scripts/generate-seed.ts from SEED_CATALOG in @pashki/core.
-- Regenerate with: pnpm --filter @pashki/db gen:seed
--
-- 55 ingredients, 97 package sizes.
--
-- Idempotent: `supabase db reset` runs this after the migrations, and running it
-- again upserts rather than duplicating. Both tables have the unique constraints
-- that makes that possible — ingredients.key and (ingredient_id, label).
--
-- base_amount and can_size are in the dimension's base unit, millilitres or
-- grams. grams_per_cup is what lets a volume measure merge into an item sold by
-- weight. Never do arithmetic on written units.

begin;

insert into public.ingredients
  (key, canonical_name, aliases, aisle, dimension, grams_per_cup, can_size)
values
  ('heavy-cream', 'heavy cream', array['heavy whipping cream', 'whipping cream', 'double cream'], 'Dairy', 'volume', null, null),
  ('half-and-half', 'half and half', array['half & half', 'single cream'], 'Dairy', 'volume', null, null),
  ('milk', 'whole milk', array['2% milk', 'skim milk', 'milk'], 'Dairy', 'volume', null, null),
  ('buttermilk', 'buttermilk', '{}'::text[], 'Dairy', 'volume', null, null),
  ('sour-cream', 'sour cream', '{}'::text[], 'Dairy', 'weight', 230, null),
  ('yogurt', 'greek yogurt', array['plain yogurt', 'yoghurt', 'yogurt'], 'Dairy', 'weight', 245, null),
  ('butter', 'unsalted butter', array['salted butter', 'butter'], 'Dairy', 'weight', 227, null),
  ('cream-cheese', 'cream cheese', '{}'::text[], 'Dairy', 'weight', 232, null),
  ('shredded-cheese', 'shredded mozzarella', array['shredded cheddar', 'mozzarella', 'cheddar', 'monterey jack', 'shredded cheese'], 'Dairy', 'weight', 113, null),
  ('parmesan', 'parmigiano reggiano', array['grated parmesan', 'parmesan', 'pecorino'], 'Dairy', 'weight', 100, null),
  ('feta', 'feta', '{}'::text[], 'Dairy', 'weight', 150, null),
  ('eggs', 'large eggs', array['eggs', 'egg'], 'Dairy', 'count', null, null),
  ('chicken-breast', 'boneless skinless chicken breast', array['chicken breasts', 'chicken breast'], 'Meat & Seafood', 'weight', null, null),
  ('chicken-thighs', 'boneless chicken thighs', array['chicken thighs', 'chicken thigh'], 'Meat & Seafood', 'weight', null, null),
  ('ground-beef', 'ground beef', array['ground chuck', 'beef mince', 'hamburger'], 'Meat & Seafood', 'weight', null, null),
  ('ground-turkey', 'ground turkey', '{}'::text[], 'Meat & Seafood', 'weight', null, null),
  ('sausage', 'italian sausage', array['sausage'], 'Meat & Seafood', 'weight', null, null),
  ('bacon', 'bacon', '{}'::text[], 'Meat & Seafood', 'weight', null, null),
  ('salmon', 'salmon fillets', array['salmon fillet', 'salmon'], 'Meat & Seafood', 'weight', null, null),
  ('shrimp', 'shrimp', array['prawns'], 'Meat & Seafood', 'weight', null, null),
  ('onion', 'yellow onion', array['white onion', 'red onion', 'onions', 'onion'], 'Produce', 'count', null, null),
  ('garlic', 'garlic cloves', array['garlic'], 'Produce', 'clove', null, null),
  ('lemon', 'lemons', array['lemon'], 'Produce', 'count', null, null),
  ('lime', 'limes', array['lime'], 'Produce', 'count', null, null),
  ('potatoes', 'russet potatoes', array['yukon gold potatoes', 'baby potatoes', 'potatoes', 'potato'], 'Produce', 'weight', null, null),
  ('carrots', 'carrots', array['carrot'], 'Produce', 'weight', null, null),
  ('celery', 'celery', '{}'::text[], 'Produce', 'count', null, null),
  ('bell-pepper', 'red bell pepper', array['green bell pepper', 'bell peppers', 'bell pepper'], 'Produce', 'count', null, null),
  ('spinach', 'baby spinach', array['spinach'], 'Produce', 'weight', null, null),
  ('tomatoes', 'roma tomatoes', array['cherry tomatoes', 'tomatoes', 'tomato'], 'Produce', 'count', null, null),
  ('mushrooms', 'cremini mushrooms', array['button mushrooms', 'mushrooms'], 'Produce', 'weight', null, null),
  ('broccoli', 'broccoli', '{}'::text[], 'Produce', 'count', null, null),
  ('avocado', 'avocados', array['avocado'], 'Produce', 'count', null, null),
  ('cilantro', 'fresh cilantro', array['cilantro', 'coriander'], 'Produce', 'bunch', null, null),
  ('parsley', 'fresh parsley', array['parsley'], 'Produce', 'bunch', null, null),
  ('basil', 'fresh basil', array['basil'], 'Produce', 'bunch', null, null),
  ('green-onions', 'green onions', array['scallions', 'spring onions', 'green onion'], 'Produce', 'bunch', null, null),
  ('olive-oil', 'extra virgin olive oil', array['olive oil'], 'Pantry', 'volume', null, null),
  ('flour', 'all purpose flour', array['all-purpose flour', 'plain flour', 'flour'], 'Pantry', 'weight', 125, null),
  ('sugar', 'granulated sugar', array['caster sugar', 'sugar'], 'Pantry', 'weight', 200, null),
  ('brown-sugar', 'brown sugar', '{}'::text[], 'Pantry', 'weight', 213, null),
  ('rice', 'jasmine rice', array['basmati rice', 'white rice', 'rice'], 'Pantry', 'weight', 185, null),
  ('pasta', 'spaghetti', array['rigatoni', 'fettuccine', 'linguine', 'penne', 'pasta'], 'Pantry', 'weight', null, null),
  ('canned-tomatoes', 'crushed tomatoes', array['diced tomatoes', 'canned tomatoes', 'chopped tomatoes', 'tomato sauce', 'passata'], 'Pantry', 'weight', 240, 425),
  ('tomato-paste', 'tomato paste', array['tomato puree'], 'Pantry', 'weight', 260, 170),
  ('sun-dried-tomatoes', 'sun dried tomatoes', array['sun-dried tomatoes'], 'Pantry', 'weight', 110, null),
  ('broth', 'chicken broth', array['chicken stock', 'vegetable broth', 'vegetable stock', 'beef broth', 'broth', 'stock'], 'Pantry', 'volume', null, 429),
  ('coconut-milk', 'coconut milk', '{}'::text[], 'Pantry', 'volume', null, 400),
  ('beans', 'black beans', array['kidney beans', 'chickpeas', 'cannellini beans', 'pinto beans'], 'Pantry', 'weight', 180, 425),
  ('soy-sauce', 'soy sauce', '{}'::text[], 'Pantry', 'volume', null, null),
  ('honey', 'honey', '{}'::text[], 'Pantry', 'volume', null, null),
  ('maple-syrup', 'maple syrup', '{}'::text[], 'Pantry', 'volume', null, null),
  ('tortillas', 'flour tortillas', array['corn tortillas', 'tortillas'], 'Bakery', 'count', null, null),
  ('bread', 'sandwich bread', array['baguette', 'bread'], 'Bakery', 'count', null, null),
  ('frozen-peas', 'frozen peas', array['frozen corn', 'frozen vegetables'], 'Frozen', 'weight', null, null)
on conflict (key) do update set
  canonical_name = excluded.canonical_name,
  aliases        = excluded.aliases,
  aisle          = excluded.aisle,
  dimension      = excluded.dimension,
  grams_per_cup  = excluded.grams_per_cup,
  can_size       = excluded.can_size,
  updated_at     = now();

-- Packages are keyed to their ingredient by catalog key rather than by a uuid, so
-- this file carries no generated ids and stays stable between runs.
insert into public.grocery_packages (ingredient_id, label, base_amount, sort_order)
select i.id, seed.label, seed.base_amount, seed.sort_order
from (values
  ('heavy-cream', '½ pint (8 oz)', 237, 0),
  ('heavy-cream', 'pint (16 oz)', 473, 1),
  ('heavy-cream', 'quart (32 oz)', 946, 2),
  ('half-and-half', 'pint', 473, 0),
  ('half-and-half', 'quart', 946, 1),
  ('milk', 'quart', 946, 0),
  ('milk', '½ gallon', 1893, 1),
  ('milk', 'gallon', 3785, 2),
  ('buttermilk', 'pint', 473, 0),
  ('buttermilk', 'quart', 946, 1),
  ('sour-cream', '8 oz tub', 227, 0),
  ('sour-cream', '16 oz tub', 454, 1),
  ('yogurt', '5.3 oz pot', 150, 0),
  ('yogurt', '16 oz tub', 454, 1),
  ('yogurt', '32 oz tub', 907, 2),
  ('butter', '1 stick', 113, 0),
  ('butter', '1 lb (4 sticks)', 454, 1),
  ('cream-cheese', '8 oz block', 227, 0),
  ('shredded-cheese', '8 oz bag', 227, 0),
  ('shredded-cheese', '16 oz bag', 454, 1),
  ('parmesan', '5 oz wedge', 142, 0),
  ('parmesan', '8 oz wedge', 227, 1),
  ('feta', '6 oz', 170, 0),
  ('feta', '8 oz', 227, 1),
  ('eggs', 'half dozen', 6, 0),
  ('eggs', 'dozen', 12, 1),
  ('eggs', '18-count', 18, 2),
  ('chicken-breast', '1 lb', 454, 0),
  ('chicken-breast', '2 lb', 907, 1),
  ('chicken-breast', '3 lb family pack', 1361, 2),
  ('chicken-thighs', '1 lb', 454, 0),
  ('chicken-thighs', '2 lb', 907, 1),
  ('ground-beef', '1 lb', 454, 0),
  ('ground-beef', '2 lb', 907, 1),
  ('ground-turkey', '1 lb', 454, 0),
  ('sausage', '1 lb', 454, 0),
  ('bacon', '12 oz pack', 340, 0),
  ('bacon', '1 lb pack', 454, 1),
  ('salmon', '1 lb', 454, 0),
  ('salmon', '1½ lb', 680, 1),
  ('shrimp', '1 lb bag', 454, 0),
  ('onion', 'loose', 1, 0),
  ('onion', '3 lb bag (~6)', 6, 1),
  ('garlic', '1 head (~10 cloves)', 10, 0),
  ('garlic', '3-pack heads', 30, 1),
  ('lemon', 'loose', 1, 0),
  ('lemon', 'bag of 5', 5, 1),
  ('lime', 'loose', 1, 0),
  ('lime', 'bag of 5', 5, 1),
  ('potatoes', 'loose lb', 454, 0),
  ('potatoes', '5 lb bag', 2268, 1),
  ('carrots', '1 lb bag', 454, 0),
  ('carrots', '2 lb bag', 907, 1),
  ('celery', '1 bunch (~8 stalks)', 8, 0),
  ('bell-pepper', 'loose', 1, 0),
  ('bell-pepper', '3-pack', 3, 1),
  ('spinach', '5 oz box', 142, 0),
  ('spinach', '10 oz box', 283, 1),
  ('tomatoes', 'loose', 1, 0),
  ('tomatoes', 'pint container', 12, 1),
  ('mushrooms', '8 oz pack', 227, 0),
  ('mushrooms', '16 oz pack', 454, 1),
  ('broccoli', '1 crown', 1, 0),
  ('avocado', 'loose', 1, 0),
  ('avocado', 'bag of 4', 4, 1),
  ('cilantro', '1 bunch', 1, 0),
  ('parsley', '1 bunch', 1, 0),
  ('basil', '1 packet', 1, 0),
  ('green-onions', '1 bunch', 1, 0),
  ('olive-oil', '17 oz bottle', 500, 0),
  ('olive-oil', '34 oz bottle', 1000, 1),
  ('flour', '2 lb bag', 907, 0),
  ('flour', '5 lb bag', 2268, 1),
  ('sugar', '2 lb bag', 907, 0),
  ('sugar', '4 lb bag', 1814, 1),
  ('brown-sugar', '1 lb bag', 454, 0),
  ('brown-sugar', '2 lb bag', 907, 1),
  ('rice', '2 lb bag', 907, 0),
  ('rice', '5 lb bag', 2268, 1),
  ('pasta', '1 lb box', 454, 0),
  ('canned-tomatoes', '15 oz can', 425, 0),
  ('canned-tomatoes', '28 oz can', 794, 1),
  ('tomato-paste', '6 oz can', 170, 0),
  ('sun-dried-tomatoes', '8 oz jar', 227, 0),
  ('broth', '14.5 oz can', 429, 0),
  ('broth', '32 oz carton', 946, 1),
  ('coconut-milk', '13.5 oz can', 400, 0),
  ('beans', '15 oz can', 425, 0),
  ('soy-sauce', '10 oz bottle', 296, 0),
  ('honey', '12 oz jar', 355, 0),
  ('maple-syrup', '8 oz bottle', 237, 0),
  ('maple-syrup', '12 oz bottle', 355, 1),
  ('tortillas', 'pack of 8', 8, 0),
  ('tortillas', 'pack of 12', 12, 1),
  ('bread', '1 loaf', 1, 0),
  ('frozen-peas', '10 oz bag', 283, 0),
  ('frozen-peas', '16 oz bag', 454, 1)
) as seed(ingredient_key, label, base_amount, sort_order)
join public.ingredients i on i.key = seed.ingredient_key
on conflict (ingredient_id, label) do update set
  base_amount = excluded.base_amount,
  sort_order  = excluded.sort_order,
  updated_at  = now();

-- A package list that shrank in SEED_CATALOG must shrink here too, or the catalog
-- would keep offering a size that no longer exists. Anything not in this run's
-- values list is removed.
delete from public.grocery_packages gp
using public.ingredients i
where gp.ingredient_id = i.id
  and (i.key, gp.label) not in (
    select seed.ingredient_key, seed.label
    from (values
  ('heavy-cream', '½ pint (8 oz)', 237, 0),
  ('heavy-cream', 'pint (16 oz)', 473, 1),
  ('heavy-cream', 'quart (32 oz)', 946, 2),
  ('half-and-half', 'pint', 473, 0),
  ('half-and-half', 'quart', 946, 1),
  ('milk', 'quart', 946, 0),
  ('milk', '½ gallon', 1893, 1),
  ('milk', 'gallon', 3785, 2),
  ('buttermilk', 'pint', 473, 0),
  ('buttermilk', 'quart', 946, 1),
  ('sour-cream', '8 oz tub', 227, 0),
  ('sour-cream', '16 oz tub', 454, 1),
  ('yogurt', '5.3 oz pot', 150, 0),
  ('yogurt', '16 oz tub', 454, 1),
  ('yogurt', '32 oz tub', 907, 2),
  ('butter', '1 stick', 113, 0),
  ('butter', '1 lb (4 sticks)', 454, 1),
  ('cream-cheese', '8 oz block', 227, 0),
  ('shredded-cheese', '8 oz bag', 227, 0),
  ('shredded-cheese', '16 oz bag', 454, 1),
  ('parmesan', '5 oz wedge', 142, 0),
  ('parmesan', '8 oz wedge', 227, 1),
  ('feta', '6 oz', 170, 0),
  ('feta', '8 oz', 227, 1),
  ('eggs', 'half dozen', 6, 0),
  ('eggs', 'dozen', 12, 1),
  ('eggs', '18-count', 18, 2),
  ('chicken-breast', '1 lb', 454, 0),
  ('chicken-breast', '2 lb', 907, 1),
  ('chicken-breast', '3 lb family pack', 1361, 2),
  ('chicken-thighs', '1 lb', 454, 0),
  ('chicken-thighs', '2 lb', 907, 1),
  ('ground-beef', '1 lb', 454, 0),
  ('ground-beef', '2 lb', 907, 1),
  ('ground-turkey', '1 lb', 454, 0),
  ('sausage', '1 lb', 454, 0),
  ('bacon', '12 oz pack', 340, 0),
  ('bacon', '1 lb pack', 454, 1),
  ('salmon', '1 lb', 454, 0),
  ('salmon', '1½ lb', 680, 1),
  ('shrimp', '1 lb bag', 454, 0),
  ('onion', 'loose', 1, 0),
  ('onion', '3 lb bag (~6)', 6, 1),
  ('garlic', '1 head (~10 cloves)', 10, 0),
  ('garlic', '3-pack heads', 30, 1),
  ('lemon', 'loose', 1, 0),
  ('lemon', 'bag of 5', 5, 1),
  ('lime', 'loose', 1, 0),
  ('lime', 'bag of 5', 5, 1),
  ('potatoes', 'loose lb', 454, 0),
  ('potatoes', '5 lb bag', 2268, 1),
  ('carrots', '1 lb bag', 454, 0),
  ('carrots', '2 lb bag', 907, 1),
  ('celery', '1 bunch (~8 stalks)', 8, 0),
  ('bell-pepper', 'loose', 1, 0),
  ('bell-pepper', '3-pack', 3, 1),
  ('spinach', '5 oz box', 142, 0),
  ('spinach', '10 oz box', 283, 1),
  ('tomatoes', 'loose', 1, 0),
  ('tomatoes', 'pint container', 12, 1),
  ('mushrooms', '8 oz pack', 227, 0),
  ('mushrooms', '16 oz pack', 454, 1),
  ('broccoli', '1 crown', 1, 0),
  ('avocado', 'loose', 1, 0),
  ('avocado', 'bag of 4', 4, 1),
  ('cilantro', '1 bunch', 1, 0),
  ('parsley', '1 bunch', 1, 0),
  ('basil', '1 packet', 1, 0),
  ('green-onions', '1 bunch', 1, 0),
  ('olive-oil', '17 oz bottle', 500, 0),
  ('olive-oil', '34 oz bottle', 1000, 1),
  ('flour', '2 lb bag', 907, 0),
  ('flour', '5 lb bag', 2268, 1),
  ('sugar', '2 lb bag', 907, 0),
  ('sugar', '4 lb bag', 1814, 1),
  ('brown-sugar', '1 lb bag', 454, 0),
  ('brown-sugar', '2 lb bag', 907, 1),
  ('rice', '2 lb bag', 907, 0),
  ('rice', '5 lb bag', 2268, 1),
  ('pasta', '1 lb box', 454, 0),
  ('canned-tomatoes', '15 oz can', 425, 0),
  ('canned-tomatoes', '28 oz can', 794, 1),
  ('tomato-paste', '6 oz can', 170, 0),
  ('sun-dried-tomatoes', '8 oz jar', 227, 0),
  ('broth', '14.5 oz can', 429, 0),
  ('broth', '32 oz carton', 946, 1),
  ('coconut-milk', '13.5 oz can', 400, 0),
  ('beans', '15 oz can', 425, 0),
  ('soy-sauce', '10 oz bottle', 296, 0),
  ('honey', '12 oz jar', 355, 0),
  ('maple-syrup', '8 oz bottle', 237, 0),
  ('maple-syrup', '12 oz bottle', 355, 1),
  ('tortillas', 'pack of 8', 8, 0),
  ('tortillas', 'pack of 12', 12, 1),
  ('bread', '1 loaf', 1, 0),
  ('frozen-peas', '10 oz bag', 283, 0),
  ('frozen-peas', '16 oz bag', 454, 1)
    ) as seed(ingredient_key, label, base_amount, sort_order)
  );

commit;
